# 公共配置
[default]
APP_NAME = "西安项目算法服务"
LOG_DIR = "logs"

# 开发环境
[development]
DEBUG = true
# 数据库
DB_HOST = "47.92.216.173"
DB_PORT = 7654
DB_USER = "postgres"
DB_PASSWORD = "zhangsan"
DB_NAME = "xian_new"
# FastAPI配置
API_HOST = "127.0.0.1"
API_PORT = 8082
# 日志配置
LOG_LEVEL = "DEBUG"

# 生产环境
[production]
DEBUG = false
# 数据库配置
DB_HOST = "10.22.245.138"
DB_PORT = 54321
DB_USER = "zaihailian"
DB_PASSWORD = "XAYJ@gis2603"
DB_NAME = "xianDC"
# FastAPI配置
API_HOST = "127.0.0.1"
API_PORT = 8081
# 日志配置
LOG_LEVEL = "WARNING"